#pragma once

#include "IExpressionNode.h"
#include "IStatementNode.h"
#include "Module.h"
#include "expressions/BinOp.h"
#include "expressions/Identifier.h"
#include "expressions/MemberReference.h"
#include "expressions/Number.h"
#include "expressions/TypeDeclarator.h"
#include "statements/Block.h"
#include "statements/Function.h"
#include "statements/Let.h"
#include "statements/Prototype.h"
#include "statements/Return.h"
#include "statements/Struct.h"